"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    if (document) {
      if (localStorage) {
        if (localStorage.getItem("theme")) {
          // let theme = localStorage.getItem("theme");
          document.documentElement.setAttribute(
            "data-theme",
            document.documentElement.getAttribute("data-theme") === "light"
              ? "dark"
              : "light"
          );
        } else {
        }
      }
    }
  }, []);
  // const toggleTheme = () => {};
  return (
    <html lang="en" data-theme="light" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased base-200`}
      >
        {children}
      </body>
    </html>
  );
}

// const useToggleTheme = () => {
//   let current_theme = "light";
//   if (document) {
//     current_theme = localStorage.getItem("theme");
//   }
//   const [theme, useTheme] = useState();
//   useEffect(() => {}, [theme]);
//   return [theme, useTheme];
// };
